Shader "Hidden/Post FX/Motion Blur" {
	Properties {
	}
	SubShader {
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 65333
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad o1.zw, v1.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[8], immediateIndexed
					dcl_constantbuffer CB1[9], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.x, cb0[6].x, l(0.500000)
					mul r0.xy, r0.xxxx, cb0[4].zwzz
					sample r1.xyzw, v1.xyxx, t0.xyzw, s1
					mul r0.xy, r0.xyxx, r1.xyxx
					dp2 r0.z, r0.xyxx, r0.xyxx
					sqrt r0.z, r0.z
					mul r0.z, r0.z, cb0[7].y
					max r0.z, r0.z, l(1.000000)
					div r0.xy, r0.xyxx, r0.zzzz
					mad r0.xy, r0.xyxx, cb0[7].yyyy, l(1.000000, 1.000000, 0.000000, 0.000000)
					mul o0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					add r0.x, -cb1[8].w, l(1.000000)
					sample r1.xyzw, v1.xyxx, t1.xyzw, s0
					mul r0.y, r1.x, cb1[7].x
					mad r0.x, r0.x, r0.y, cb1[7].y
					mad r0.y, -cb1[8].w, r0.y, l(1.000000)
					div o0.z, r0.y, r0.x
					mov o0.w, l(0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 88610
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad o1.zw, v1.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[8], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mad r0.xyzw, cb0[2].xyxy, l(-0.500000, -0.500000, 0.500000, -0.500000), v1.xyxy
					sample r1.xyzw, r0.xyxx, t0.xyzw, s0
					sample r0.xyzw, r0.zwzz, t0.xyzw, s0
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mad r0.zw, r1.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
					mul r0.xyzw, r0.xyzw, cb0[7].xxxx
					dp2 r1.x, r0.zwzz, r0.zwzz
					dp2 r1.y, r0.xyxx, r0.xyxx
					lt r1.x, r1.x, r1.y
					movc r0.xy, r1.xxxx, r0.xyxx, r0.zwzz
					dp2 r0.z, r0.xyxx, r0.xyxx
					mad r1.xyzw, cb0[2].xyxy, l(-0.500000, 0.500000, 0.500000, 0.500000), v1.xyxy
					sample r2.xyzw, r1.xyxx, t0.xyzw, s0
					sample r1.xyzw, r1.zwzz, t0.xyzw, s0
					mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mad r1.zw, r2.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
					mul r1.xyzw, r1.xyzw, cb0[7].xxxx
					dp2 r0.w, r1.zwzz, r1.zwzz
					lt r0.z, r0.z, r0.w
					movc r0.xy, r0.zzzz, r1.zwzz, r0.xyxx
					dp2 r0.z, r0.xyxx, r0.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					lt r0.z, r0.z, r0.w
					movc o0.xy, r0.zzzz, r1.xyxx, r0.xyxx
					mov o0.zw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 159453
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad o1.zw, v1.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mad r0.xyzw, cb0[2].xyxy, l(-0.500000, -0.500000, 0.500000, -0.500000), v1.xyxy
					sample r1.xyzw, r0.xyxx, t0.xyzw, s0
					sample r0.xyzw, r0.zwzz, t0.xyzw, s0
					dp2 r0.z, r1.xyxx, r1.xyxx
					dp2 r0.w, r0.xyxx, r0.xyxx
					lt r0.z, r0.z, r0.w
					movc r0.xy, r0.zzzz, r0.xyxx, r1.xyxx
					dp2 r0.z, r0.xyxx, r0.xyxx
					mad r1.xyzw, cb0[2].xyxy, l(-0.500000, 0.500000, 0.500000, 0.500000), v1.xyxy
					sample r2.xyzw, r1.xyxx, t0.xyzw, s0
					sample r1.xyzw, r1.zwzz, t0.xyzw, s0
					dp2 r0.w, r2.xyxx, r2.xyxx
					lt r0.z, r0.z, r0.w
					movc r0.xy, r0.zzzz, r2.xyxx, r0.xyxx
					dp2 r0.z, r0.xyxx, r0.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					lt r0.z, r0.z, r0.w
					movc o0.xy, r0.zzzz, r1.xyxx, r0.xyxx
					mov o0.zw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 245116
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad o1.zw, v1.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 5
					mad r0.xy, cb0[2].xyxx, cb0[6].zwzz, v1.xyxx
					mov r1.yz, l(0,0,0,0)
					mov r1.xw, cb0[2].xxxy
					mov r0.zw, l(0,0,0,0)
					mov r2.x, l(0)
					loop 
					  ige r2.y, r2.x, cb0[6].y
					  breakc_nz r2.y
					  itof r2.y, r2.x
					  mad r2.yz, r1.xxyx, r2.yyyy, r0.xxyx
					  mov r3.xy, r0.zwzz
					  mov r2.w, l(0)
					  loop 
					    ige r3.z, r2.w, cb0[6].y
					    breakc_nz r3.z
					    itof r3.z, r2.w
					    mad r3.zw, r1.zzzw, r3.zzzz, r2.yyyz
					    sample r4.xyzw, r3.zwzz, t0.xyzw, s0
					    dp2 r3.z, r3.xyxx, r3.xyxx
					    dp2 r3.w, r4.xyxx, r4.xyxx
					    lt r3.z, r3.z, r3.w
					    movc r3.xy, r3.zzzz, r4.xyxx, r3.xyxx
					    iadd r2.w, r2.w, l(1)
					  endloop 
					  mov r0.zw, r3.xxxy
					  iadd r2.x, r2.x, l(1)
					endloop 
					mov o0.xy, r0.zwzz
					mov o0.zw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 278035
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad o1.zw, v1.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 4
					mad r0.xyzw, cb0[2].yyxy, l(0.000000, 1.000000, 1.000000, 1.000000), v1.xyxy
					sample r1.xyzw, r0.xyxx, t0.xyzw, s0
					sample r0.xyzw, r0.zwzz, t0.xyzw, s0
					dp2 r0.z, r1.xyxx, r1.xyxx
					dp2 r0.w, r0.xyxx, r0.xyxx
					lt r0.z, r0.z, r0.w
					movc r0.xy, r0.zzzz, r0.xyxx, r1.xyxx
					dp2 r0.z, r0.xyxx, r0.xyxx
					mad r1.xyzw, cb0[2].xyxy, l(1.000000, 0.000000, -1.000000, 1.000000), v1.xyxy
					sample r2.xyzw, r1.zwzz, t0.xyzw, s0
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					dp2 r0.w, r2.xyxx, r2.xyxx
					lt r0.z, r0.w, r0.z
					movc r0.xy, r0.zzzz, r0.xyxx, r2.xyxx
					dp2 r0.z, r0.xyxx, r0.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					sample r2.xyzw, v1.xyxx, t0.xyzw, s0
					mul r1.zw, r2.xxxy, l(0.000000, 0.000000, 1.010000, 1.010000)
					dp2 r2.x, r1.zwzz, r1.zwzz
					lt r0.w, r2.x, r0.w
					movc r1.xy, r0.wwww, r1.xyxx, r1.zwzz
					dp2 r0.w, r1.xyxx, r1.xyxx
					mad r2.xyzw, -cb0[2].xyxy, l(-1.000000, 1.000000, 1.000000, 0.000000), v1.xyxy
					sample r3.xyzw, r2.zwzz, t0.xyzw, s0
					sample r2.xyzw, r2.xyxx, t0.xyzw, s0
					dp2 r1.z, r3.xyxx, r3.xyxx
					lt r0.w, r1.z, r0.w
					movc r1.xy, r0.wwww, r1.xyxx, r3.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					lt r0.z, r0.w, r0.z
					movc r0.xy, r0.zzzz, r0.xyxx, r1.xyxx
					dp2 r0.z, r0.xyxx, r0.xyxx
					dp2 r0.w, r2.xyxx, r2.xyxx
					mad r1.xyzw, -cb0[2].xyyy, l(1.000000, 1.000000, 0.000000, 1.000000), v1.xyxy
					sample r3.xyzw, r1.zwzz, t0.xyzw, s0
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					dp2 r1.z, r3.xyxx, r3.xyxx
					lt r0.w, r1.z, r0.w
					movc r1.zw, r0.wwww, r2.xxxy, r3.xxxy
					dp2 r0.w, r1.zwzz, r1.zwzz
					dp2 r2.x, r1.xyxx, r1.xyxx
					lt r0.w, r2.x, r0.w
					movc r1.xy, r0.wwww, r1.zwzz, r1.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					lt r0.z, r0.w, r0.z
					movc r0.xy, r0.zzzz, r0.xyxx, r1.xyxx
					mul o0.xy, r0.xyxx, l(0.990099, 0.990099, 0.000000, 0.000000)
					mov o0.zw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 358164
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					lt r0.x, cb0[2].y, l(0.000000)
					add r0.y, -v1.y, l(1.000000)
					movc o1.w, r0.x, r0.y, v1.y
					mov o1.xyz, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[8], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v1.zw
					dcl_output o0.xyzw
					dcl_temps 10
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					add r1.xy, v1.zwzz, l(2.000000, 0.000000, 0.000000, 0.000000)
					mul r1.xy, r1.xyxx, cb1[6].xyxx
					round_ni r1.xy, r1.xyxx
					dp2 r1.x, l(0.067111, 0.005837, 0.000000, 0.000000), r1.xyxx
					frc r1.x, r1.x
					mul r1.x, r1.x, l(52.982918)
					frc r1.x, r1.x
					mul r1.x, r1.x, l(6.283185)
					sincos r1.x, r2.x, r1.x
					mov r2.y, r1.x
					mul r1.xy, r2.xyxx, cb0[5].zwzz
					mad r1.xy, r1.xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), v1.zwzz
					sample r1.xyzw, r1.xyxx, t2.xyzw, s2
					dp2 r1.z, r1.xyxx, r1.xyxx
					sqrt r1.z, r1.z
					lt r1.w, r1.z, l(2.000000)
					if_nz r1.w
					  mov o0.xyzw, r0.xyzw
					  ret 
					endif 
					sample_l r2.xyzw, v1.zwzz, t1.xyzw, s1, l(0.000000)
					mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r2.xy, r2.xyxx, cb0[7].xxxx
					dp2 r1.w, r2.xyxx, r2.xyxx
					sqrt r1.w, r1.w
					max r3.xy, r1.wwww, l(0.500000, 1.000000, 0.000000, 0.000000)
					div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.z
					add r2.w, r3.x, r3.x
					lt r2.w, r1.z, r2.w
					div r3.x, r1.z, r3.x
					mul r2.xy, r2.xyxx, r3.xxxx
					movc r2.xy, r2.wwww, r2.xyxx, r1.xyxx
					mul r2.w, r1.z, l(0.500000)
					min r2.w, r2.w, cb0[7].z
					round_ni r2.w, r2.w
					div r3.x, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
					mul r3.zw, v1.xxxy, cb1[6].xxxy
					round_ni r3.zw, r3.zzzw
					dp2 r3.z, l(0.067111, 0.005837, 0.000000, 0.000000), r3.zwzz
					frc r3.z, r3.z
					mul r3.zw, r3.zzzx, l(0.000000, 0.000000, 52.982918, 0.250000)
					frc r3.z, r3.z
					add r3.z, r3.z, l(-0.500000)
					mad r4.x, -r3.x, l(0.500000), l(1.000000)
					mov r5.w, l(1.000000)
					mov r6.xyzw, l(0,0,0,0)
					mov r4.y, r4.x
					mov r4.z, l(0)
					mov r4.w, r3.y
					loop 
					  ge r7.x, r3.w, r4.y
					  breakc_nz r7.x
					  mul r7.xy, r4.zzzz, l(0.250000, 0.500000, 0.000000, 0.000000)
					  frc r7.xy, r7.xyxx
					  lt r7.xy, l(0.499000, 0.499000, 0.000000, 0.000000), r7.xyxx
					  movc r7.xz, r7.xxxx, r2.xxyx, r1.xxyx
					  movc r7.w, r7.y, -r4.y, r4.y
					  mad r7.w, r3.z, r3.x, r7.w
					  mul r7.xz, r7.wwww, r7.xxzx
					  mad r8.xy, r7.xzxx, cb0[2].xyxx, v1.xyxx
					  mad r7.xz, r7.xxzx, cb0[5].xxyx, v1.zzwz
					  sample_l r8.xyzw, r8.xyxx, t0.xyzw, s0, l(0.000000)
					  sample_l r9.xyzw, r7.xzxx, t1.xyzw, s1, l(0.000000)
					  mad r7.xz, r9.xxyx, l(2.000000, 0.000000, 2.000000, 0.000000), l(-1.000000, 0.000000, -1.000000, 0.000000)
					  mul r7.xz, r7.xxzx, cb0[7].xxxx
					  add r8.w, r2.z, -r9.z
					  mul r8.w, r1.w, r8.w
					  mul_sat r8.w, r8.w, l(20.000000)
					  dp2 r7.x, r7.xzxx, r7.xzxx
					  sqrt r7.x, r7.x
					  add r7.x, -r4.w, r7.x
					  mad r7.x, r8.w, r7.x, r4.w
					  mad_sat r7.z, -r1.z, |r7.w|, r7.x
					  div r7.z, r7.z, r7.x
					  add r7.w, -r4.y, l(1.200000)
					  mul r7.z, r7.w, r7.z
					  mov r5.xyz, r8.xyzx
					  mad r6.xyzw, r5.xyzw, r7.zzzz, r6.xyzw
					  max r4.w, r4.w, r7.x
					  add r5.x, -r3.x, r4.y
					  movc r4.y, r7.y, r5.x, r4.y
					  add r4.z, r4.z, l(1.000000)
					endloop 
					dp2 r1.x, r4.wwww, r2.wwww
					div r1.x, l(1.200000), r1.x
					mov r2.xyz, r0.xyzx
					mov r2.w, l(1.000000)
					mad r1.xyzw, r2.xyzw, r1.xxxx, r6.xyzw
					div o0.xyz, r1.xyzx, r1.wwww
					mov o0.w, r0.w
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 396106
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					mov o0.xyzw, v0.xyzw
					mad o1.xy, v1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.000000, 1.000000, 0.000000, 0.000000)
					mov o1.zw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_COLORSPACE_GAMMA" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					mov o0.xyzw, v0.xyzw
					mad o1.xy, v1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.000000, 1.000000, 0.000000, 0.000000)
					mov o1.zw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					// SV_Target                1   xyzw        1   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_output o1.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					log r0.xyz, r0.xyzx
					mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					dp3 o0.xyzw, l(0.299000, 0.587000, 0.114000, 0.000000), r0.xyzx
					mul r0.x, v1.x, cb0[6].x
					mul r0.x, r0.x, l(0.500000)
					round_ni r0.y, r0.x
					frc r0.x, r0.x
					lt r0.x, l(0.500000), r0.x
					movc r0.xzw, r0.xxxx, l(0.500000,0,-0.418688,-0.081312), l(-0.168736,0,-0.331264,0.500000)
					mad r0.y, r0.y, l(2.000000), l(1.000000)
					add r1.x, cb0[6].z, l(-1.000000)
					mul r1.x, r0.y, r1.x
					mov r1.y, v1.y
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					log r1.xyz, r1.xyzx
					mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r1.xyz, r1.xyzx
					mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					dp3 r0.x, r0.xzwx, r1.xyzx
					add o1.xyzw, r0.xxxx, l(0.500000, 0.500000, 0.500000, 0.500000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_COLORSPACE_GAMMA" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					// SV_Target                1   xyzw        1   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_output o1.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					dp3 o0.xyzw, l(0.299000, 0.587000, 0.114000, 0.000000), r0.xyzx
					mul r0.x, v1.x, cb0[6].x
					mul r0.x, r0.x, l(0.500000)
					round_ni r0.y, r0.x
					frc r0.x, r0.x
					lt r0.x, l(0.500000), r0.x
					movc r0.xzw, r0.xxxx, l(0.500000,0,-0.418688,-0.081312), l(-0.168736,0,-0.331264,0.500000)
					mad r0.y, r0.y, l(2.000000), l(1.000000)
					add r1.x, cb0[6].z, l(-1.000000)
					mul r1.x, r0.y, r1.x
					mov r1.y, v1.y
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					dp3 r0.x, r0.xzwx, r1.xyzx
					add o1.xyzw, r0.xxxx, l(0.500000, 0.500000, 0.500000, 0.500000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 484791
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					lt r0.x, cb0[2].y, l(0.000000)
					add r0.y, -v1.y, l(1.000000)
					movc o1.w, r0.x, r0.y, v1.y
					mov o1.xyz, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_COLORSPACE_GAMMA" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					lt r0.x, cb0[2].y, l(0.000000)
					add r0.y, -v1.y, l(1.000000)
					movc o1.w, r0.x, r0.y, v1.y
					mov o1.xyz, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_sampler s5, mode_default
					dcl_sampler s6, mode_default
					dcl_sampler s7, mode_default
					dcl_sampler s8, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_resource_texture2d (float,float,float,float) t5
					dcl_resource_texture2d (float,float,float,float) t6
					dcl_resource_texture2d (float,float,float,float) t7
					dcl_resource_texture2d (float,float,float,float) t8
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v1.zw
					dcl_output o0.xyzw
					dcl_temps 5
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mov o0.w, r0.w
					log r0.xyz, r0.xyzx
					mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					sample r1.xyzw, v1.zwzz, t1.xyzw, s1
					mul r0.w, v1.z, cb0[2].z
					mul r0.w, r0.w, l(0.500000)
					round_ni r0.w, r0.w
					mad r0.w, r0.w, l(2.000000), l(0.500000)
					mad r2.z, r0.w, cb0[2].x, cb0[2].x
					mul r2.x, r0.w, cb0[2].x
					mov r2.yw, v1.wwww
					sample r3.xyzw, r2.zwzz, t2.xyzw, s5
					add r0.w, r3.x, l(-0.500000)
					mul r3.xy, r0.wwww, l(1.402000, 0.714140, 0.000000, 0.000000)
					sample r4.xyzw, r2.xyxx, t2.xyzw, s5
					add r0.w, r4.x, l(-0.500000)
					mad r3.z, r0.w, l(-0.344140), -r3.y
					mul r3.w, r0.w, l(1.772000)
					add r1.xyz, r1.xxxx, r3.xzwx
					mad r0.xyz, r1.xyzx, cb0[7].wwww, r0.xyzx
					sample r1.xyzw, v1.zwzz, t3.xyzw, s2
					sample r3.xyzw, r2.zwzz, t4.xyzw, s6
					add r0.w, r3.x, l(-0.500000)
					mul r3.xy, r0.wwww, l(1.402000, 0.714140, 0.000000, 0.000000)
					sample r4.xyzw, r2.xyxx, t4.xyzw, s6
					add r0.w, r4.x, l(-0.500000)
					mad r3.z, r0.w, l(-0.344140), -r3.y
					mul r3.w, r0.w, l(1.772000)
					add r1.xyz, r1.xxxx, r3.xzwx
					mad r0.xyz, r1.xyzx, cb0[8].xxxx, r0.xyzx
					sample r1.xyzw, r2.zwzz, t6.xyzw, s7
					sample r3.xyzw, r2.zwzz, t8.xyzw, s8
					add r0.w, r3.x, l(-0.500000)
					mul r3.xy, r0.wwww, l(1.402000, 0.714140, 0.000000, 0.000000)
					add r0.w, r1.x, l(-0.500000)
					mul r1.xy, r0.wwww, l(1.402000, 0.714140, 0.000000, 0.000000)
					sample r4.xyzw, r2.xyxx, t6.xyzw, s7
					sample r2.xyzw, r2.xyxx, t8.xyzw, s8
					add r0.w, r2.x, l(-0.500000)
					add r2.x, r4.x, l(-0.500000)
					mad r1.z, r2.x, l(-0.344140), -r1.y
					mul r1.w, r2.x, l(1.772000)
					sample r2.xyzw, v1.zwzz, t5.xyzw, s3
					add r1.xyz, r1.xzwx, r2.xxxx
					mad r0.xyz, r1.xyzx, cb0[8].yyyy, r0.xyzx
					mad r3.z, r0.w, l(-0.344140), -r3.y
					mul r3.w, r0.w, l(1.772000)
					sample r1.xyzw, v1.zwzz, t7.xyzw, s4
					add r1.xyz, r3.xzwx, r1.xxxx
					mad r0.xyz, r1.xyzx, cb0[8].zzzz, r0.xyzx
					add r0.w, cb0[7].w, cb0[8].x
					add r0.w, r0.w, cb0[8].y
					add r0.w, r0.w, cb0[8].z
					add r0.w, r0.w, l(1.000000)
					div r0.xyz, r0.xyzx, r0.wwww
					mad r1.xyz, r0.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r1.xyz, r0.xyzx, r1.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul o0.xyz, r0.xyzx, r1.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_COLORSPACE_GAMMA" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_sampler s5, mode_default
					dcl_sampler s6, mode_default
					dcl_sampler s7, mode_default
					dcl_sampler s8, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_resource_texture2d (float,float,float,float) t5
					dcl_resource_texture2d (float,float,float,float) t6
					dcl_resource_texture2d (float,float,float,float) t7
					dcl_resource_texture2d (float,float,float,float) t8
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v1.zw
					dcl_output o0.xyzw
					dcl_temps 5
					sample r0.xyzw, v1.zwzz, t1.xyzw, s1
					mul r0.y, v1.z, cb0[2].z
					mul r0.y, r0.y, l(0.500000)
					round_ni r0.y, r0.y
					mad r0.y, r0.y, l(2.000000), l(0.500000)
					mad r1.z, r0.y, cb0[2].x, cb0[2].x
					mul r1.x, r0.y, cb0[2].x
					mov r1.yw, v1.wwww
					sample r2.xyzw, r1.zwzz, t2.xyzw, s5
					add r0.y, r2.x, l(-0.500000)
					mul r2.xy, r0.yyyy, l(1.402000, 0.714140, 0.000000, 0.000000)
					sample r3.xyzw, r1.xyxx, t2.xyzw, s5
					add r0.y, r3.x, l(-0.500000)
					mad r2.z, r0.y, l(-0.344140), -r2.y
					mul r2.w, r0.y, l(1.772000)
					add r0.xyz, r0.xxxx, r2.xzwx
					sample r2.xyzw, v1.xyxx, t0.xyzw, s0
					mad r0.xyz, r0.xyzx, cb0[7].wwww, r2.xyzx
					mov o0.w, r2.w
					sample r2.xyzw, v1.zwzz, t3.xyzw, s2
					sample r3.xyzw, r1.zwzz, t4.xyzw, s6
					add r0.w, r3.x, l(-0.500000)
					mul r3.xy, r0.wwww, l(1.402000, 0.714140, 0.000000, 0.000000)
					sample r4.xyzw, r1.xyxx, t4.xyzw, s6
					add r0.w, r4.x, l(-0.500000)
					mad r3.z, r0.w, l(-0.344140), -r3.y
					mul r3.w, r0.w, l(1.772000)
					add r2.xyz, r2.xxxx, r3.xzwx
					mad r0.xyz, r2.xyzx, cb0[8].xxxx, r0.xyzx
					sample r2.xyzw, r1.zwzz, t6.xyzw, s7
					sample r3.xyzw, r1.zwzz, t8.xyzw, s8
					add r0.w, r3.x, l(-0.500000)
					mul r3.xy, r0.wwww, l(1.402000, 0.714140, 0.000000, 0.000000)
					add r0.w, r2.x, l(-0.500000)
					mul r2.xy, r0.wwww, l(1.402000, 0.714140, 0.000000, 0.000000)
					sample r4.xyzw, r1.xyxx, t6.xyzw, s7
					sample r1.xyzw, r1.xyxx, t8.xyzw, s8
					add r0.w, r1.x, l(-0.500000)
					add r1.x, r4.x, l(-0.500000)
					mad r2.z, r1.x, l(-0.344140), -r2.y
					mul r2.w, r1.x, l(1.772000)
					sample r1.xyzw, v1.zwzz, t5.xyzw, s3
					add r1.xyz, r2.xzwx, r1.xxxx
					mad r0.xyz, r1.xyzx, cb0[8].yyyy, r0.xyzx
					mad r3.z, r0.w, l(-0.344140), -r3.y
					mul r3.w, r0.w, l(1.772000)
					sample r1.xyzw, v1.zwzz, t7.xyzw, s4
					add r1.xyz, r3.xzwx, r1.xxxx
					mad r0.xyz, r1.xyzx, cb0[8].zzzz, r0.xyzx
					add r0.w, cb0[7].w, cb0[8].x
					add r0.w, r0.w, cb0[8].y
					add r0.w, r0.w, cb0[8].z
					add r0.w, r0.w, l(1.000000)
					div o0.xyz, r0.xyzx, r0.wwww
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 539235
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					lt r0.x, cb0[2].y, l(0.000000)
					add r0.y, -v1.y, l(1.000000)
					movc o1.w, r0.x, r0.y, v1.y
					mov o1.xyz, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t1.xyzw, s1
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					mad r0.xyz, r0.xyzx, cb0[7].wwww, r1.xyzx
					mov o0.w, r1.w
					sample r1.xyzw, v1.xyxx, t2.xyzw, s2
					mad r0.xyz, r1.xyzx, cb0[8].xxxx, r0.xyzx
					sample r1.xyzw, v1.xyxx, t3.xyzw, s3
					mad r0.xyz, r1.xyzx, cb0[8].yyyy, r0.xyzx
					sample r1.xyzw, v1.xyxx, t4.xyzw, s4
					mad r0.xyz, r1.xyzx, cb0[8].zzzz, r0.xyzx
					add r0.w, cb0[7].w, cb0[8].x
					add r0.w, r0.w, cb0[8].y
					add r0.w, r0.w, cb0[8].z
					add r0.w, r0.w, l(1.000000)
					div o0.xyz, r0.xyzx, r0.wwww
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}