Shader "Hidden/Colorful/Chromatic Aberration" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_Refraction ("Refraction Index (RGB)", Vector) = (1,1.005,1.01,0)
	}
	SubShader {
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 45438
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mov o0.w, l(1.000000)
					add r0.xyz, -cb0[3].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mul r1.xyz, r0.zzzz, l(0.000000, 0.000000, -1.000000, 0.000000)
					mul r0.xyzw, r0.xxyy, l(0.000000, -1.000000, 0.000000, -1.000000)
					mad r2.xy, v1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mov r2.z, l(1.000000)
					mad r1.xyz, cb0[3].zzzz, r2.xyzx, -r1.xyzx
					div r1.xy, r1.xyxx, r1.zzzz
					add r1.xy, r1.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mul r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mov o0.z, r1.z
					mad r1.xyz, cb0[3].xxxx, r2.xyzx, -r0.xxyx
					mad r0.xyz, cb0[3].yyyy, r2.xyzx, -r0.zzwz
					div r0.xy, r0.xyxx, r0.zzzz
					add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.y, r0.y
					div r0.xy, r1.xyxx, r1.zzzz
					add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 81403
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					mov o0.w, r0.w
					add r0.xyz, -cb0[3].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mul r1.xyz, r0.zzzz, l(0.000000, 0.000000, -1.000000, 0.000000)
					mul r0.xyzw, r0.xxyy, l(0.000000, -1.000000, 0.000000, -1.000000)
					mad r2.xy, v1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mov r2.z, l(1.000000)
					mad r1.xyz, cb0[3].zzzz, r2.xyzx, -r1.xyzx
					div r1.xy, r1.xyxx, r1.zzzz
					add r1.xy, r1.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mul r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					mov o0.z, r1.z
					mad r1.xyz, cb0[3].xxxx, r2.xyzx, -r0.xxyx
					mad r0.xyz, cb0[3].yyyy, r2.xyzx, -r0.zzwz
					div r0.xy, r0.xyxx, r0.zzzz
					add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.y, r0.y
					div r0.xy, r1.xyxx, r1.zzzz
					add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}