Shader "Hidden/Colorful/Glitch" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
	}
	SubShader {
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 34588
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.xy, v1.xyxx, cb0[2].yyyy
					mul r0.z, cb0[2].x, cb1[0].y
					round_ni r0.xyz, r0.xyzx
					mul r0.xy, r0.zzzz, r0.xyxx
					dp2 r0.x, r0.xyxx, l(127.099998, 311.700012, 0.000000, 0.000000)
					sincos r0.x, null, r0.x
					mul r0.x, r0.x, l(43758.546875)
					frc r0.x, r0.x
					mul r0.y, r0.x, r0.x
					mul r0.x, r0.y, r0.x
					mul r0.y, r0.y, r0.y
					mul r0.y, r0.y, r0.y
					mul r1.xyzw, r0.zzzz, l(7.234100, 1.000000, 7.000000, 1.000000)
					mul r0.zw, r0.zzzz, l(0.000000, 0.000000, 13.000000, 1.000000)
					dp2 r0.z, r0.zwzz, l(127.099998, 311.700012, 0.000000, 0.000000)
					sincos r0.z, null, r0.z
					mul r0.z, r0.z, l(43758.546875)
					dp2 r0.w, r1.xyxx, l(127.099998, 311.700012, 0.000000, 0.000000)
					dp2 r1.x, r1.zwzz, l(127.099998, 311.700012, 0.000000, 0.000000)
					sincos r1.x, null, r1.x
					mul r1.x, r1.x, l(43758.546875)
					frc r1.x, r1.x
					sincos r0.w, null, r0.w
					mul r0.w, r0.w, l(43758.546875)
					frc r0.zw, r0.zzzw
					log r0.w, r0.w
					mul r0.w, r0.w, l(17.000000)
					exp r0.w, r0.w
					mul r0.w, r0.w, cb0[2].z
					mad r0.x, r0.y, r0.x, -r0.w
					mul r0.x, r0.x, l(0.050000)
					mul r2.z, r0.z, r0.x
					mul r2.x, r1.x, r0.x
					mov r2.yw, l(0,0,0,0)
					add r0.xy, -r2.zwzz, v1.xyxx
					add r0.zw, r2.xxxy, v1.xxxy
					sample r1.xyzw, r0.zwzz, t0.xyzw, s0
					mov o0.y, r1.y
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.z, r0.z
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					mov o0.x, r0.x
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 92837
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 1
					mul r0.x, cb0[2].x, cb1[0].y
					mul r0.y, r0.x, l(0.031250)
					round_ni r0.y, r0.y
					mad r0.x, -r0.y, l(32.000000), r0.x
					mul r0.y, r0.x, l(4.000000)
					round_ni r0.y, r0.y
					mul r0.y, r0.y, l(37.500000)
					mul r0.z, v1.y, l(16.000000)
					round_ni r0.z, r0.z
					mad r0.y, r0.z, l(0.062500), r0.y
					dp2 r0.y, r0.yyyy, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.y, null, r0.y
					mul r0.y, r0.y, l(43758.546875)
					frc r0.y, r0.y
					mul r0.y, r0.y, l(16.000000)
					mul r0.x, r0.y, r0.x
					round_ni r0.x, r0.x
					div r0.x, r0.x, r0.y
					mad r0.x, r0.x, l(5.000000), v1.y
					mul r0.xy, r0.xxxx, l(11.000000, 7.000000, 0.000000, 0.000000)
					round_ni r0.xy, r0.xyxx
					mul r0.xy, r0.xyxx, l(0.090909, 0.142857, 0.000000, 0.000000)
					dp2 r0.y, r0.yyyy, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r0.x, r0.xxxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.xy, null, r0.xyxx
					mul r0.xy, r0.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r0.xy, r0.xyxx
					mul r0.y, r0.y, l(0.500000)
					mad r0.x, r0.x, l(0.500000), r0.y
					mad r0.x, r0.x, l(2.000000), l(-1.000000)
					lt r0.y, l(0.000000), r0.x
					lt r0.z, r0.x, l(0.000000)
					iadd r0.y, -r0.y, r0.z
					itof r0.y, r0.y
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.x, -r0.z, |r0.x|
					div_sat r0.x, r0.x, cb0[2].y
					mul r0.x, r0.x, r0.y
					mul r0.x, r0.x, cb0[2].z
					mov r0.y, l(0)
					add_sat r0.xy, r0.xyxx, v1.xyxx
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 167394
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.x, v1.y, l(16.000000)
					mul r0.y, cb0[2].x, cb1[0].y
					mul r0.z, r0.y, l(0.031250)
					round_ni r0.xz, r0.xxzx
					mad r0.y, -r0.z, l(32.000000), r0.y
					mul r0.zw, r0.yyyy, l(0.000000, 0.000000, 4.000000, 8.000000)
					round_ni r0.zw, r0.zzzw
					mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 37.500000, 0.125000)
					mad r0.x, r0.x, l(0.062500), r0.z
					dp2 r0.z, r0.wwww, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.z, null, r0.z
					mul r0.z, r0.z, l(43758.546875)
					dp2 r0.x, r0.xxxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.x, null, r0.x
					mul r0.x, r0.x, l(43758.546875)
					frc r0.xz, r0.xxzx
					mul r0.x, r0.x, l(16.000000)
					mul r0.y, r0.x, r0.y
					round_ni r0.y, r0.y
					div r0.x, r0.y, r0.x
					mad r0.x, r0.x, l(5.000000), v1.y
					mul r0.xy, r0.xxxx, l(11.000000, 7.000000, 0.000000, 0.000000)
					round_ni r0.xy, r0.xyxx
					mul r0.xy, r0.xyxx, l(0.090909, 0.142857, 0.000000, 0.000000)
					dp2 r0.y, r0.yyyy, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r0.x, r0.xxxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.xy, null, r0.xyxx
					mul r0.xy, r0.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r0.xy, r0.xyxx
					mul r0.y, r0.y, l(0.500000)
					mad r0.x, r0.x, l(0.500000), r0.y
					mad r0.x, r0.x, l(2.000000), l(-1.000000)
					lt r0.y, l(0.000000), r0.x
					lt r0.w, r0.x, l(0.000000)
					iadd r0.y, -r0.y, r0.w
					itof r0.y, r0.y
					add r0.w, -cb0[2].y, l(1.000000)
					add r0.x, -r0.w, |r0.x|
					div_sat r0.x, r0.x, cb0[2].y
					mul r0.x, r0.x, r0.y
					mul r0.x, r0.x, cb0[2].z
					mov r0.y, l(0)
					add_sat r1.xy, r0.xyxx, v1.xyxx
					add r0.x, -r1.y, l(1.000000)
					mad r0.y, cb0[2].y, l(-0.025000), l(1.000000)
					lt r0.y, r0.y, r0.z
					movc r1.z, r0.y, r0.x, r1.y
					sample r0.xyzw, r1.xzxx, t0.xyzw, s0
					mov o0.xyz, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 207926
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.x, cb0[2].x, cb1[0].y
					mul r0.y, r0.x, l(0.031250)
					round_ni r0.y, r0.y
					mad r0.x, -r0.y, l(32.000000), r0.x
					mul r0.y, r0.x, l(4.000000)
					round_ni r0.y, r0.y
					mul r0.y, r0.y, l(37.500000)
					mul r0.z, v1.y, l(16.000000)
					round_ni r0.z, r0.z
					mad r0.y, r0.z, l(0.062500), r0.y
					dp2 r0.y, r0.yyyy, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.y, null, r0.y
					mul r0.y, r0.y, l(43758.546875)
					frc r0.y, r0.y
					mul r0.y, r0.y, l(16.000000)
					mul r0.x, r0.y, r0.x
					round_ni r0.x, r0.x
					div r0.x, r0.x, r0.y
					mad r0.x, r0.x, l(5.000000), v1.y
					mul r0.xy, r0.xxxx, l(11.000000, 7.000000, 0.000000, 0.000000)
					round_ni r0.xy, r0.xyxx
					mul r0.xy, r0.xyxx, l(0.090909, 0.142857, 0.000000, 0.000000)
					dp2 r0.y, r0.yyyy, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r0.x, r0.xxxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.xy, null, r0.xyxx
					mul r0.xy, r0.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r0.xy, r0.xyxx
					mul r0.y, r0.y, l(0.500000)
					mad r0.x, r0.x, l(0.500000), r0.y
					mad r0.x, r0.x, l(2.000000), l(-1.000000)
					lt r0.y, l(0.000000), r0.x
					lt r0.z, r0.x, l(0.000000)
					iadd r0.y, -r0.y, r0.z
					itof r0.y, r0.y
					add r0.z, -cb0[2].y, l(1.000000)
					add r0.x, -r0.z, |r0.x|
					div_sat r0.x, r0.x, cb0[2].y
					mad_sat r0.z, -r0.y, r0.x, cb0[2].w
					mul r0.w, r0.x, r0.y
					mad_sat r0.x, r0.y, r0.x, -cb0[2].w
					mul r0.y, |r0.w|, l(3.000000)
					mad r0.y, -r0.y, r0.z, l(1.000000)
					mul r1.x, r0.w, cb0[2].z
					mul r0.z, r0.w, l(0.125000)
					mov r1.y, l(0)
					add_sat r1.xy, r1.xyxx, v1.xyxx
					sample r1.xyzw, r1.xyxx, t0.xyzw, s0
					dp3 r0.w, r1.xyzx, l(-0.147130, -0.288860, 0.436000, 0.000000)
					div r2.x, r0.w, r0.y
					dp3 r0.y, r1.xyzx, l(0.615000, -0.514990, -0.100010, 0.000000)
					dp3 r0.w, r1.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
					mad r2.y, r0.z, r0.x, r0.y
					dp2 r0.x, l(-0.394650, -0.580600, 0.000000, 0.000000), r2.xyxx
					mad o0.xz, r2.yyxy, l(1.139830, 0.000000, 2.032110, 0.000000), r0.wwww
					add o0.y, r0.x, r0.w
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 270365
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.x, v1.y, l(16.000000)
					mul r0.y, cb0[2].x, cb1[0].y
					mul r0.z, r0.y, l(0.031250)
					round_ni r0.xz, r0.xxzx
					mad r0.y, -r0.z, l(32.000000), r0.y
					mul r0.zw, r0.yyyy, l(0.000000, 0.000000, 4.000000, 8.000000)
					round_ni r0.zw, r0.zzzw
					mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 37.500000, 0.125000)
					mad r0.x, r0.x, l(0.062500), r0.z
					dp2 r0.z, r0.wwww, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.z, null, r0.z
					mul r0.z, r0.z, l(43758.546875)
					dp2 r0.x, r0.xxxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.x, null, r0.x
					mul r0.x, r0.x, l(43758.546875)
					frc r0.xz, r0.xxzx
					mul r0.x, r0.x, l(16.000000)
					mul r0.y, r0.x, r0.y
					round_ni r0.y, r0.y
					div r0.x, r0.y, r0.x
					mad r0.x, r0.x, l(5.000000), v1.y
					mul r0.xy, r0.xxxx, l(11.000000, 7.000000, 0.000000, 0.000000)
					round_ni r0.xy, r0.xyxx
					mul r0.xy, r0.xyxx, l(0.090909, 0.142857, 0.000000, 0.000000)
					dp2 r0.y, r0.yyyy, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r0.x, r0.xxxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.xy, null, r0.xyxx
					mul r0.xy, r0.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r0.xy, r0.xyxx
					mul r0.y, r0.y, l(0.500000)
					mad r0.x, r0.x, l(0.500000), r0.y
					mad r0.x, r0.x, l(2.000000), l(-1.000000)
					lt r0.y, l(0.000000), r0.x
					lt r0.w, r0.x, l(0.000000)
					iadd r0.y, -r0.y, r0.w
					itof r0.y, r0.y
					add r0.w, -cb0[2].y, l(1.000000)
					add r0.x, -r0.w, |r0.x|
					div_sat r0.x, r0.x, cb0[2].y
					mad_sat r0.w, -r0.y, r0.x, cb0[2].w
					mul r1.x, r0.x, r0.y
					mad_sat r0.x, r0.y, r0.x, -cb0[2].w
					mul r0.y, |r1.x|, l(3.000000)
					mad r0.y, -r0.y, r0.w, l(1.000000)
					mad r0.w, cb0[2].y, l(-0.025000), l(1.000000)
					lt r0.z, r0.w, r0.z
					mul r2.x, r1.x, cb0[2].z
					mul r0.w, r1.x, l(0.125000)
					mov r2.y, l(0)
					add_sat r1.xy, r2.xyxx, v1.xyxx
					add r1.w, -r1.y, l(1.000000)
					movc r1.z, r0.z, r1.w, r1.y
					sample r1.xyzw, r1.xzxx, t0.xyzw, s0
					dp3 r0.z, r1.xyzx, l(-0.147130, -0.288860, 0.436000, 0.000000)
					div r2.x, r0.z, r0.y
					dp3 r0.y, r1.xyzx, l(0.615000, -0.514990, -0.100010, 0.000000)
					dp3 r0.z, r1.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
					mad r2.y, r0.w, r0.x, r0.y
					dp2 r0.x, l(-0.394650, -0.580600, 0.000000, 0.000000), r2.xyxx
					mad o0.xz, r2.yyxy, l(1.139830, 0.000000, 2.032110, 0.000000), r0.zzzz
					add o0.y, r0.x, r0.z
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}