Shader "Hidden/EfficientBlur" {
	Properties {
		_MainTex ("Texture", 2D) = "white" {}
	}
	SubShader {
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 46568
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 1   xy          1     NONE   float   xy  
					// TEXCOORD                 2     zw        1     NONE   float     zw
					// TEXCOORD                 3   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mul r0.xyzw, cb0[2].xyxy, cb0[4].xxxx
					mad r1.xyzw, r0.xyzy, l(0.500000, 0.500000, -0.500000, 0.500000), v1.xyxy
					mad r0.xyzw, r0.xwzw, l(0.500000, -0.500000, -0.500000, -0.500000), v1.xyxy
					mad o2.xyzw, r0.xyzw, cb0[3].xyxy, cb0[3].zwzw
					mad o1.xyzw, r1.xyzw, cb0[3].xyxy, cb0[3].zwzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 1   xy          1     NONE   float   xy  
					// TEXCOORD                 2     zw        1     NONE   float     zw
					// TEXCOORD                 3   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v1.zw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					sample r1.xyzw, v1.zwzz, t0.xyzw, s0
					add r0.xyzw, r0.xyzw, r1.xyzw
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					add r0.xyzw, r0.xyzw, r1.xyzw
					sample r1.xyzw, v2.zwzz, t0.xyzw, s0
					add r0.xyzw, r0.xyzw, r1.xyzw
					mul o0.xyzw, r0.xyzw, l(0.250000, 0.250000, 0.250000, 0.250000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}