Shader "UI/TranslucentImage" {
	Properties {
		[PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
		[HideInInspector] _BlurTex ("Blur Texture", 2D) = "gray" {}
		_Vibrancy ("Vibrancy", Float) = 1
		_Brightness ("Brightness", Float) = 0
		_Flatten ("Flatten", Float) = 0
		_StencilComp ("Stencil Comparison", Float) = 8
		_Stencil ("Stencil ID", Float) = 0
		_StencilOp ("Stencil Operation", Float) = 0
		_StencilWriteMask ("Stencil Write Mask", Float) = 255
		_StencilReadMask ("Stencil Read Mask", Float) = 255
		_ColorMask ("Color Mask", Float) = 15
		[Toggle(UNITY_UI_ALPHACLIP)] _UseUIAlphaClip ("Use Alpha Clip", Float) = 0
	}
	SubShader {
		Tags { "CanUseSpriteAtlas" = "true" "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			Tags { "CanUseSpriteAtlas" = "true" "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ColorMask 0 -1
			ZWrite Off
			Cull Off
			Stencil {
				ReadMask 0
				WriteMask 0
				Comp Disabled
				Pass Keep
				Fail Keep
				ZFail Keep
			}
			GpuProgramID 3219
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 3     zw        2     NONE   float     zw
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        4     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mov o2.xy, v2.xyxx
					mov o2.zw, v3.xxxy
					mov o3.xyzw, v0.xyzw
					mul r1.xyz, r0.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mov o4.zw, r0.zzzw
					mul r1.w, r1.y, cb0[5].x
					add o4.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_ALPHACLIP" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 3     zw        2     NONE   float     zw
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        4     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mov o2.xy, v2.xyxx
					mov o2.zw, v3.xxxy
					mov o3.xyzw, v0.xyzw
					mul r1.xyz, r0.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mov o4.zw, r0.zzzw
					mul r1.w, r1.y, cb0[5].x
					add o4.xy, r1.zzzz, r1.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 3     zw        2     NONE   float     z 
					// TEXCOORD                 1   xyzw        3     NONE   float   xy  
					// TEXCOORD                 2   xyzw        4     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.z
					dcl_input_ps linear v3.xy
					dcl_input_ps linear v4.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					div r0.xy, v4.xyxx, v4.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					add r1.xyz, -r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mad_sat r0.xyz, cb0[4].yyyy, r1.xyzx, r0.xyzx
					dp3 r0.w, r0.xyzx, l(0.039682, 0.458022, 0.006097, 0.000000)
					add r0.xyz, -r0.wwww, r0.xyzx
					mad_sat r0.xyz, cb0[4].xxxx, r0.xyzx, r0.wwww
					add_sat r0.xyz, r0.xyzx, cb0[4].zzzz
					sample r1.xyzw, v2.xyxx, t1.xyzw, s0
					add r1.xyzw, r1.xyzw, cb0[2].xyzw
					mad r1.xyz, r1.xyzx, v1.xyzx, -r0.xyzx
					mad o0.xyz, v2.zzzz, r1.xyzx, r0.xyzx
					mul r0.x, r1.w, v1.w
					ge r0.yz, v3.xxyx, cb0[3].xxyx
					and r0.yz, r0.yyzy, l(0, 0x3f800000, 0x3f800000, 0)
					ge r1.xy, cb0[3].zwzz, v3.xyxx
					and r1.xy, r1.xyxx, l(0x3f800000, 0x3f800000, 0, 0)
					mul r0.yz, r0.yyzy, r1.xxyx
					mul r0.y, r0.z, r0.y
					mul o0.w, r0.y, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_ALPHACLIP" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 3     zw        2     NONE   float     z 
					// TEXCOORD                 1   xyzw        3     NONE   float   xy  
					// TEXCOORD                 2   xyzw        4     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.z
					dcl_input_ps linear v3.xy
					dcl_input_ps linear v4.xyw
					dcl_output o0.xyzw
					dcl_temps 3
					ge r0.xy, v3.xyxx, cb0[3].xyxx
					ge r0.zw, cb0[3].zzzw, v3.xxxy
					and r0.xyzw, r0.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
					mul r0.xy, r0.zwzz, r0.xyxx
					mul r0.x, r0.y, r0.x
					sample r1.xyzw, v2.xyxx, t1.xyzw, s0
					add r1.xyzw, r1.xyzw, cb0[2].xyzw
					mul r0.y, r1.w, v1.w
					mad r0.z, r0.y, r0.x, l(-0.001000)
					mul r0.x, r0.x, r0.y
					mov o0.w, r0.x
					lt r0.x, r0.z, l(0.000000)
					discard_nz r0.x
					div r0.xy, v4.xyxx, v4.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					add r2.xyz, -r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mad_sat r0.xyz, cb0[4].yyyy, r2.xyzx, r0.xyzx
					dp3 r0.w, r0.xyzx, l(0.039682, 0.458022, 0.006097, 0.000000)
					add r0.xyz, -r0.wwww, r0.xyzx
					mad_sat r0.xyz, cb0[4].xxxx, r0.xyzx, r0.wwww
					add_sat r0.xyz, r0.xyzx, cb0[4].zzzz
					mad r1.xyz, r1.xyzx, v1.xyzx, -r0.xyzx
					mad o0.xyz, v2.zzzz, r1.xyzx, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}